<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Assignment 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Assignment2_files/libs/clipboard/clipboard.min.js"></script>
<script src="Assignment2_files/libs/quarto-html/quarto.js"></script>
<script src="Assignment2_files/libs/quarto-html/popper.min.js"></script>
<script src="Assignment2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Assignment2_files/libs/quarto-html/anchor.min.js"></script>
<link href="Assignment2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Assignment2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Assignment2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Assignment2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Assignment2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="assignment-2" class="level1">
<h1>Assignment 2</h1>
<section id="task-a.-plotting-monthly-averages-of-temparature-volume-price-and-wind-production." class="level2">
<h2 class="anchored" data-anchor-id="task-a.-plotting-monthly-averages-of-temparature-volume-price-and-wind-production.">Task A. Plotting monthly averages of temparature, volume, price and wind production.</h2>
<p>We looked at the relationships between temperature, volume, price, and wind power production. These variables have different scales, so we scaled their monthly averages to compare them better. We focused on the last year of the sample to keep the plot easy to read.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data frame of monthly averages of the variables volume, price, </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># temperature and wind_production in long format.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df_avg_long <span class="ot">&lt;-</span> </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select the specified variables</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(date, volume, temperature, price, wind_production) <span class="sc">%&gt;%</span> </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate monthly averages for each variable</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">year_month =</span> <span class="fu">floor_date</span>(date, <span class="st">"month"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(year_month) <span class="sc">%&gt;%</span> </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_vol =</span> <span class="fu">mean</span>(volume, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_temp =</span> <span class="fu">mean</span>(temperature, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_price =</span> <span class="fu">mean</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_wind =</span> <span class="fu">mean</span>(wind_production, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Scale the values </span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_vol =</span> <span class="fu">scale</span>(avg_vol), </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_wind =</span> <span class="fu">scale</span>(avg_wind),</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_temp =</span> <span class="fu">scale</span>(avg_temp),</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">avg_price =</span> <span class="fu">scale</span>(avg_price)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Pivot to long format</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pivot_longer</span>(</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>      <span class="at">cols =</span> <span class="sc">-</span>year_month,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>      <span class="at">names_to =</span> <span class="st">"variable"</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>      <span class="at">values_to =</span> <span class="st">"scaled values"</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the specified variables</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df_avg_long <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(year_month) <span class="sc">%&gt;%</span> </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">60</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">x =</span> year_month,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">y =</span> <span class="st">`</span><span class="at">scaled values</span><span class="st">`</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> variable</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship between variables"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Months"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Scaled values"</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Upon examining the provided plot, a few notable patterns and relationships emerge. Firstly, we notice a strong inverse relationship between average temperature and volume. As the temperature dips, notably around January and then again toward the end of the year, there’s a noticeable rise in volume, suggesting that colder months might drive up the demand for energy. This is reinforced by the trend of wind power production. Wind production seems to rise during periods of colder temperatures, which could indicate that colder months are, in general, windier.</p>
<p>In terms of pricing, there’s a clear spike around April. This might be influenced by multiple factors, but its correlation with the other variables at that specific time is less direct. While volume and temperature show a consistent inverse relationship, the relationship between price and other variables is less linear, suggesting that other external factors might play a role in influencing the price.</p>
<p>The relationships highlighted here offer valuable insights, but a deeper analysis of the data and potential external influences will likely provide a more comprehensive understanding.</p>
</section>
<section id="task-b.-why-will-a-ols-regression-on-quantity-not-provide-an-estimate-of-demand" class="level2">
<h2 class="anchored" data-anchor-id="task-b.-why-will-a-ols-regression-on-quantity-not-provide-an-estimate-of-demand">Task B. Why will a OLS regression on quantity not provide an estimate of demand?</h2>
<p>Using an OLS regression on quantity with price as the only predictor isn’t good enough to accurately estimate demand, even with added controls. There’s a problem with endogeneity because price and quantity in markets are decided at the same time. Also, important variables like consumer income, advertising, and seasonality might be left out, which can introduce bias. Mistakes in measuring price or quantity can also affect the accuracy of our results. The OLS method assumes a straight line relationship between variables, but if the demand curves aren’t straight lines, this becomes an issue. Another concern is heteroskedasticity, where the variability of the error changes with different price levels, affecting the reliability of standard errors. The changing behavior of demand and its seasonality might not be fully captured by OLS. To get a more detailed and accurate picture of demand, methods like instrumental variable regression are often better. Improving data quality and including controls for relevant factors can also make our estimates more precise.</p>
</section>
<section id="task-c.-considering-choice-of-instrument-for-price-when-estimating-demand" class="level2">
<h2 class="anchored" data-anchor-id="task-c.-considering-choice-of-instrument-for-price-when-estimating-demand">Task C. Considering choice of instrument for price when estimating demand</h2>
<p>When picking an instrument for price in estimating demand, the instrument’s validity is crucial. Valid instruments should be relevant, exogenous (not linked to unobserved factors), and shouldn’t directly affect the dependent variable.</p>
<section id="is-temperature-a-valid-instrument-for-price-in-estimating-demand" class="level3">
<h3 class="anchored" data-anchor-id="is-temperature-a-valid-instrument-for-price-in-estimating-demand">Is temperature a valid instrument for price in estimating demand?</h3>
<p>Using temperature as an instrument for price could be problematic. Temperature often changes with factors that can also influence demand, like the time of year or consumer habits. If temperature is connected with unseen demand shifts, it’s not a valid choice because of these links.</p>
</section>
<section id="could-magazine-levels-and-wind-power-production-be-good-price-instruments-when-estimating-demand" class="level3">
<h3 class="anchored" data-anchor-id="could-magazine-levels-and-wind-power-production-be-good-price-instruments-when-estimating-demand">Could magazine levels and wind power production be good price instruments when estimating demand?</h3>
<p>Both magazine levels and wind power production might be effective instruments for price. They need to influence the price and remain exogenous, meaning they shouldn’t be linked with unseen factors affecting demand. It’s essential to carefully assess their exogeneity by testing if they’re associated with other unobserved variables.</p>
</section>
<section id="why-do-we-need-to-adjust-for-seasonality-and-temperature" class="level3">
<h3 class="anchored" data-anchor-id="why-do-we-need-to-adjust-for-seasonality-and-temperature">Why do we need to adjust for seasonality and temperature?</h3>
<p>Adjusting for the time of year and temperature ensures our demand estimates are more accurate. The time of year can cause regular shifts in demand not related to price, while temperature can change demand directly. By adjusting for these, we’re making sure other factors aren’t distorting our demand estimates.</p>
</section>
<section id="how-can-adjusting-for-weekday-and-year-help" class="level3">
<h3 class="anchored" data-anchor-id="how-can-adjusting-for-weekday-and-year-help">How can adjusting for weekday and year help?</h3>
<p>Including weekday and year adjustments can account for different demand patterns. For instance, demand might differ on weekdays compared to weekends. Adjusting for year can capture larger trends or bigger economic impacts on demand. By including these adjustments, we get a clearer picture of demand that’s not clouded by these other factors.</p>
</section>
</section>
<section id="task-d.-providing-a-table-of-regression-results" class="level2">
<h2 class="anchored" data-anchor-id="task-d.-providing-a-table-of-regression-results">Task D. Providing a table of regression results</h2>
<p>Using the provided equations, we conducted several regression analyses. To enhance clarity, we rescaled some of the data, particularly dividing volume and wind power production by 1,000. We also added variables to our dataset indicating the year, month, and weekday for each observation.</p>
<p>We chose to present a table of all regression result, but for enhanced clarity we omitted dummies for year, month and day i all regressions, and the regression statistics as they will not be of value to the following discussion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new variables in data frame containing the dummies for</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># year, month and day in which the observation is made and scale variables.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df_new <span class="ot">&lt;-</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">volume =</span> volume <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">wind_production =</span> wind_production <span class="sc">/</span> <span class="dv">1000</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">as.factor</span>(<span class="fu">year</span>(date)),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">as.factor</span>(<span class="fu">month</span>(date)),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">weekday =</span> <span class="fu">as.factor</span>(<span class="fu">wday</span>(date,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">label =</span> <span class="cn">FALSE</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">week_start =</span> <span class="dv">1</span>))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform specified regressions</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># First stage</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>first_stage <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  price <span class="sc">~</span> magazine_level <span class="sc">+</span> temperature <span class="sc">+</span> wind_production <span class="sc">+</span> year <span class="sc">+</span> month <span class="sc">+</span> weekday,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_new</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Reduced form</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>reduced_form <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  volume <span class="sc">~</span> magazine_level <span class="sc">+</span> temperature <span class="sc">+</span> wind_production <span class="sc">+</span> year <span class="sc">+</span> month <span class="sc">+</span> weekday,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_new</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># IV/2SLS </span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>iv_model <span class="ot">&lt;-</span> <span class="fu">ivreg</span>(</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  volume <span class="sc">~</span> price <span class="sc">+</span> temperature <span class="sc">+</span> year <span class="sc">+</span> month <span class="sc">+</span> weekday </span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="sc">|</span> magazine_level <span class="sc">+</span> temperature <span class="sc">+</span> wind_production <span class="sc">+</span> year <span class="sc">+</span> month <span class="sc">+</span> weekday, </span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_new</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co"># OLS</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>ols_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  volume <span class="sc">~</span> price <span class="sc">+</span> temperature <span class="sc">+</span> year <span class="sc">+</span> month <span class="sc">+</span> weekday,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_new</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression table of all regression.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Omitting statistics to make the table more readable.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Note! Scaling of variables 'volume' and 'wind_production' of 10^-3, and </span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># that all dummies is omitted from the regression table.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Table including all regressions"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  first_stage,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  reduced_form,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  iv_model,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  ols_model,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">omit =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>, <span class="st">"weekday"</span>),</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">omit.table.layout =</span> <span class="st">"sn"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">dep.var.caption =</span> <span class="st">"First stage (1) | Reduced form (2) | IV/2SLS (3) |OLS (4)"</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Table including all regressions
============================================================================
                 First stage (1) | Reduced form (2) | IV/2SLS (3) |OLS (4)  
                ------------------------------------------------------------
                     price                         volume                   
                      OLS            OLS        instrumental       OLS      
                                                  variable                  
                      (1)            (2)            (3)            (4)      
----------------------------------------------------------------------------
magazine_level     -0.380***       1.282***                                 
                    (0.022)        (0.162)                                  
                                                                            
price                                             1.831***       1.173***   
                                                  (0.364)        (0.146)    
                                                                            
temperature        -0.321***      -12.755***     -12.036***     -12.341***  
                    (0.036)        (0.270)        (0.331)        (0.292)    
                                                                            
wind_production    -0.035***      -0.356***                                 
                    (0.002)        (0.019)                                  
                                                                            
Constant           63.158***     1,062.206***   1,037.639***   1,064.506*** 
                    (1.287)        (9.653)        (15.479)       (7.300)    
                                                                            
============================================================================
============================================================================</code></pre>
</div>
</div>
<p>With basis in the results above, we will take a closer look at the OLS and IV/2SLS regressions, provide a short description of their purpose and our findings, and a comparison of the two models.</p>
<section id="ols-regression" class="level3">
<h3 class="anchored" data-anchor-id="ols-regression">OLS regression</h3>
<p>The Ordinary Least Squares (OLS) regression serves as our benchmark to determine the level of bias introduced by endogeneity. Endogeneity, which arises when an independent variable correlates with the error term, can skew results, leading to biased or unreliable estimates.</p>
<p>For the OLS regression, coefficients for price and temperature are 1.173 and -12.341 respectively. The accompanying error terms are small and positive, suggesting that our model fits the data well for the variables chosen.</p>
</section>
<section id="iv2sls-regression" class="level3">
<h3 class="anchored" data-anchor-id="iv2sls-regression">IV/2SLS regression</h3>
<p>The Instrumental Variable/Two-Stage Least Squares (IV/2SLS) regression aims to estimate the demand for electricity in the power market while accounting for endogeneity. The model’s foundation lies in the first stage and reduced form regressions.</p>
<p>In the IV/2SLS model, with volume as the dependent variable, both price and temperature coefficients are statistically significant at the 1% level. Their values are 1.831 and -12.036 respectively. Interestingly, an increase in price corresponds to an increase in volume, a trend that might be influenced by limited supply during peak demand months due to magazine levels.</p>
</section>
<section id="comparison-of-the-two-models" class="level3">
<h3 class="anchored" data-anchor-id="comparison-of-the-two-models">Comparison of the two models</h3>
<p>When comparing the IV/2SLS model to the OLS benchmark, there are slight variations in the coefficients. For instance, the price coefficient in IV/2SLS is 1.831, while in OLS it’s 1.173. Bigger price changes could highlight these differences even more, showing the importance of using both models in various situations.</p>
<p>While the OLS model provides a good starting point, the IV/2SLS model offers deeper insights by addressing potential endogeneity concerns. The observed differences in the coefficients between the two models highlight the importance of considering both techniques, especially in an economic context where even small variations can have large implications.</p>
</section>
</section>
<section id="task-e.-commenting-on-the-first-stage-regression" class="level2">
<h2 class="anchored" data-anchor-id="task-e.-commenting-on-the-first-stage-regression">Task E. Commenting on the first stage regression</h2>
<p>The first stage regression is designed to address endogeneity by identifying instrumental variables that are correlated to the endogenous variable but is uncorrelated with the error term. This process helps to ensure consistent and unbiased parameter estimates.</p>
<p>In this stage, we examine the relationship between several instruments, namely magazine levels, temperature, and wind production, and the variable we aim to instrument, which is the electricity price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression table for first stage, including stats</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"First stage"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  first_stage,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">omit =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>, <span class="st">"weekday"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
First stage
===============================================
                        Dependent variable:    
                    ---------------------------
                               price           
-----------------------------------------------
magazine_level               -0.380***         
                              (0.022)          
                                               
temperature                  -0.321***         
                              (0.036)          
                                               
wind_production              -0.035***         
                              (0.002)          
                                               
Constant                     63.158***         
                              (1.287)          
                                               
-----------------------------------------------
Observations                   2,556           
R2                             0.717           
Adjusted R2                    0.714           
Residual Std. Error      5.285 (df = 2529)     
F Statistic         246.224*** (df = 26; 2529) 
===============================================
Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>The coefficients associated with magazine levels, temperatures, and wind production are -0.380, -0.321, and -0.035 respectively. All of these coefficients are negative and statistically significant at the 1% level. This suggests that as these variables increase, the price of electricity (the dependent variable) tends to decrease. Additionally, the error terms for these coefficients are small and positive.</p>
<p>The negative relationship between magazine levels and price introduced above is intuitive: when magazine levels are high, it typically indicates a supply of electricity greater than the demand. Furthermore, during colder months, inflows to the magazines are reduced, which can lead to higher electricity prices due to diminished supply.</p>
<p>Similarly, it is logical for the electricity price to decrease with rising temperatures, as warmer conditions reduce the need for heating in homes and buildings. This inverse relationship is evident in the plot (see task A), which shows the average volume (depicted in blue) and average temperature (shown in green) displaying opposite trends across months.</p>
<p>Lastly, wind production, which can vary seasonally and often peaks during winter months, exhibits a mild correlation with magazine levels, a trend also visible in the plot (task A). The influence of these instruments on the price of electricity aligns well with economic reasoning.</p>
</section>
<section id="task-f.-commenting-on-the-reduced-form" class="level2">
<h2 class="anchored" data-anchor-id="task-f.-commenting-on-the-reduced-form">Task F. Commenting on the reduced form</h2>
<p>We substituted the endogenous variable, electricity demand at time <em>t</em>, with the instruments in our reduced form regression. This regression took volume as the dependent variable, using magazine level, temperature, and wind production as the independent variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression table for reduced form, including stats</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">title =</span> <span class="st">"Reduced form"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  reduced_form,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"text"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">omit =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>, <span class="st">"weekday"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Reduced form
================================================
                        Dependent variable:     
                    ----------------------------
                               volume           
------------------------------------------------
magazine_level                1.282***          
                              (0.162)           
                                                
temperature                  -12.755***         
                              (0.270)           
                                                
wind_production              -0.356***          
                              (0.019)           
                                                
Constant                    1,062.206***        
                              (9.653)           
                                                
------------------------------------------------
Observations                   2,556            
R2                             0.944            
Adjusted R2                    0.943            
Residual Std. Error      39.648 (df = 2529)     
F Statistic         1,627.381*** (df = 26; 2529)
================================================
Note:                *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>In the table of regression results all coefficients were significant at the 1% level, and error terms were consistently small and positive. We noticed a very high goodness-of-fit at 94.4%. Despite this result indicating that out model fit the data really well, such a high goodness-of-fit raises suspicion of potential data loss or other errors in the estimation.</p>
<p>F-statistic was statistically significant 1% level giving a value of 1627.381 which is very high. This implies that the variables included in the model are jointly statistically significant on the on demanded quantity.</p>
<p>Lastly, we investigated whether the coefficients from the first stage and the reduced form were as we expected based on the discussion earlier about instrument validity (see task C for clarity). We observed a simultaneity endogeneity issue. Price and volume can influence each other, questioning the validity of the instruments. For instance, a price increase due to electricity market changes would reduce consumption. Conversely, changes in volume can affect the price.</p>
</section>
<section id="task-g.-application-of-the-iv2sls-estimates" class="level2">
<h2 class="anchored" data-anchor-id="task-g.-application-of-the-iv2sls-estimates">Task G. Application of the IV/2SLS estimates</h2>
<p>Applying our estimates of the coefficient for price in our IV/2SLS regression (the structural form) of 1.831, a permanent increase in electricity prices of 10 EUR / MWh would suggest an increase in the dependent value, volume, og 18.831 units. Remember that before performing the regression, we divided the ‘volume’ variable by 1,000, thus one unit of the variable volume is 1,000 MWh . Therefore, we can conclude with a basis in our estimates that a permanent increase in electricity prices of 10 EUR / MWh we expect the volume to increase by 1,831 MWh.</p>
<p>Our results is rather surprising. Standard economic theory suggests that an increase in prices usually reduces the demand. However, the source of this surprising result is the problems of endogeneity as discussed earlier. As we are trying to determine the effect of price on volume, we didn’t include the other explanatory variables magazine level and wind production that is correlated with both price and volume, thus resulting in a biased regression coefficient for price.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> volume, <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Assignment2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(volume<span class="sc">~</span>price <span class="sc">+</span>magazine_level <span class="sc">+</span> temperature <span class="sc">+</span> wind_production <span class="sc">+</span> year <span class="sc">+</span> month <span class="sc">+</span> weekday, <span class="at">data =</span> df_new)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(reg1, <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">omit =</span> <span class="fu">c</span>(<span class="st">"year"</span>, <span class="st">"month"</span>, <span class="st">"week"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
================================================
                        Dependent variable:     
                    ----------------------------
                               volume           
------------------------------------------------
price                         1.047***          
                              (0.148)           
                                                
magazine_level                1.680***          
                              (0.170)           
                                                
temperature                  -12.419***         
                              (0.271)           
                                                
wind_production              -0.320***          
                              (0.019)           
                                                
Constant                     996.107***         
                              (13.360)          
                                                
------------------------------------------------
Observations                   2,556            
R2                             0.945            
Adjusted R2                    0.944            
Residual Std. Error      39.268 (df = 2528)     
F Statistic         1,599.442*** (df = 27; 2528)
================================================
Note:                *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>